Repository erxes/erxes, pull requests merged in 2020-10, with the labels that each got.

#2348 Webhooks
  ui/public/images/icons/webhook.png
  ui/src/modules/leads/containers/CreateLead.tsx
  ui/src/modules/leads/types.ts
  ui/src/modules/settings/constants.ts
  ui/src/modules/settings/integrations/components/common/CommonFieldForm.tsx
  ui/src/modules/settings/integrations/components/common/IntegrationListItem.tsx
  ui/src/modules/settings/integrations/components/webhook/Form.tsx
  ui/src/modules/settings/integrations/constants.ts
  ui/src/modules/settings/integrations/containers/common/IntegrationForm.tsx
  ui/src/modules/settings/integrations/containers/common/IntegrationList.tsx
  ui/src/modules/settings/integrations/graphql/mutations.ts
  ui/src/modules/settings/integrations/graphql/queries.ts
  ui/src/modules/settings/integrations/types.ts
  ui/src/modules/settings/main/components/Settings.tsx
  ui/src/modules/settings/routes.tsx
  ui/src/modules/settings/scripts/components/InstallCode.tsx
  ui/src/modules/settings/webhook/components/WebhookForm.tsx
  ui/src/modules/settings/webhook/components/WebhookList.tsx
  ui/src/modules/settings/webhook/containers/WebhookList.tsx
  ui/src/modules/settings/webhook/graphql/index.ts
  ui/src/modules/settings/webhook/graphql/mutations.ts
  ui/src/modules/settings/webhook/graphql/queries.ts
  ui/src/modules/settings/webhook/routes.tsx
  ui/src/modules/settings/webhook/styles.ts
  ui/src/modules/settings/webhook/types.ts
  widgets/client/utils.ts
Labels: type: feature

#2368 Update README.md
  CHANGELOG.md
  README.md
  package.json
Labels: area/docs, status/ready-for-merge

#2293 fixed typos
  docs/docs/user/contacts.md
Labels: swag-submission

#2389 Enhance Send email
  ui/src/modules/common/components/ModalTrigger.tsx
  ui/src/modules/common/components/submenu/Submenu.tsx
  ui/src/modules/common/styles/global-styles.ts
  ui/src/modules/customers/components/common/ActionSection.tsx
  ui/src/modules/customers/components/detail/CustomerDetails.tsx
  ui/src/modules/inbox/components/Inbox.tsx
  ui/src/modules/inbox/components/leftSidebar/Sidebar.tsx
  ui/src/modules/inbox/components/leftSidebar/styles.ts
  ui/src/modules/layout/components/Header.tsx
  ui/src/modules/settings/integrations/components/mail/SendEmail.tsx
  ui/src/modules/settings/integrations/routes.tsx
  ui/src/modules/settings/main/components/Settings.tsx
Labels: hacktoberfest-accepted

#2393 Solved issue #2360
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  package.json
Labels: Hacktoberfest, area/docs, hacktoberfest-accepted, swag-submission

#2283 fix: incorrect issues page links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area/ui, hacktoberfest-accepted

#2412 Auto completion
  ui/src/modules/common/components/AutoCompletionSelect.tsx
  ui/src/modules/companies/components/common/InfoSection.tsx
  ui/src/modules/companies/components/list/CompanyForm.tsx
  ui/src/modules/companies/containers/CompanyForm.tsx
  ui/src/modules/companies/graphql/queries.ts
  ui/src/modules/customers/components/list/CustomerForm.tsx
  ui/src/modules/customers/containers/CustomerForm.tsx
  ui/src/modules/customers/graphql/queries.ts
Labels: hacktoberfest-accepted

#2425 fix(board): fix confirmation message when archive list. close #2424
  ui/src/locales/en.json
  ui/src/modules/boards/components/stage/Stage.tsx
  ui/src/modules/boards/containers/Stage.tsx
Labels: hacktoberfest-accepted

#2426 refactor(general): standardized buttons
  ui/src/modules/boards/components/portable/AddForm.tsx
  ui/src/modules/boards/components/stage/AddForm.tsx
  ui/src/modules/common/components/Chooser.tsx
  ui/src/modules/common/components/DataWithLoader.tsx
  ui/src/modules/companies/components/detail/CompaniesMerge.tsx
  ui/src/modules/companies/components/list/CompaniesList.tsx
  ui/src/modules/customers/components/common/ActionSection.tsx
  ui/src/modules/customers/components/detail/CustomersMerge.tsx
  ui/src/modules/customers/components/list/CustomersList.tsx
  ui/src/modules/engage/components/AutoAndManualForm.tsx
  ui/src/modules/engage/components/VisitorForm.tsx
  ui/src/modules/forms/components/FieldForm.tsx
  ui/src/modules/inbox/components/conversationDetail/workarea/facebook/ReplyingMessage.tsx
  ui/src/modules/inbox/components/conversationDetail/workarea/responseTemplate/Modal.tsx
  ui/src/modules/knowledgeBase/components/article/ArticleForm.tsx
  ui/src/modules/knowledgeBase/components/article/ArticleList.tsx
  ui/src/modules/knowledgeBase/containers/article/ArticleForm.tsx
  ui/src/modules/leads/components/Lead.tsx
  ui/src/modules/settings/brands/components/BrandForm.tsx
  ui/src/modules/settings/brands/components/ChooseBrand.tsx
  ui/src/modules/settings/brands/containers/Sidebar.tsx
  ui/src/modules/settings/common/components/Form.tsx
  ui/src/modules/settings/email/components/Signature.tsx
  ui/src/modules/settings/integrations/components/common/ManageIntegrations.tsx
  ui/src/modules/settings/integrations/containers/SelectBrand.tsx
  ui/src/modules/settings/profile/components/ChangePassword.tsx
  ui/src/modules/settings/profile/components/PasswordConfirmation.tsx
  ui/src/modules/settings/properties/components/GenerateCustomFields.tsx
  ui/src/modules/settings/properties/components/ManageColumns.tsx
  ui/src/modules/settings/properties/components/PropertyForm.tsx
  ui/src/modules/settings/properties/components/PropertyGroupForm.tsx
  ui/src/modules/settings/properties/containers/PropertyForm.tsx
  ui/src/modules/settings/properties/containers/PropertyGroupForm.tsx
  ui/src/modules/settings/team/components/UserInvitationForm.tsx
  ui/src/modules/settings/team/components/UserList.tsx
  ui/src/modules/settings/team/components/UserResetPasswordForm.tsx
  ui/src/modules/tags/components/Form.tsx
  ui/src/modules/tags/containers/List.tsx
Labels: hacktoberfest-accepted
