Repository erxes/erxes, pull requests merged in 2020-08, with the labels that each got.

#2199 apply basic click-jack attack defense
  ui/src/modules/common/utils/index.tsx
  ui/src/modules/layout/components/AuthLayout.tsx
  ui/src/modules/layout/components/MainLayout.tsx
Labels: type: enhancement

#2218 Update README.md
  README.md
Labels: area/docs

#2226 Added Licence Badge
  CHANGELOG.md
  README.md
  package.json
Labels: area/docs

#2244 Update system-config.md
  docs/docs/administrator/system-config.md
Labels: area/docs

#2243 Update troubleshooting.md
  docs/docs/developer/troubleshooting.md
Labels: area/docs

#2209 add some punchuations and add perfect size of image
  README.md
Labels: swag-submission
