Repository erxes/erxes, pull requests merged in 2020-11, with the labels that each got.

#2440 Remove localization from import&export sidebar
  ui/src/modules/settings/importHistory/components/Histories.tsx
Labels: Hacktoberfest

#2444 Update readme and other changes
  README.md
  docs/blog/2020-04-02-install-erxes-with-heroku.md
  docs/docs/administrator/system-config.md
  docs/docs/installation/centos8.md
  docs/docs/installation/debian10.md
  docs/docs/installation/redhat8.md
  docs/docs/overview/overview.md
  docs/docs/user/knowledge-base.md
  docs/docs/user/popups.md
  docs/docs/user/script-install.md
  ui/src/modules/segments/components/Sidebar.tsx
  ui/src/modules/settings/general/components/EngageSettingsContent.tsx
  ui/src/modules/settings/general/components/GeneralSettings.tsx
  ui/src/modules/settings/general/components/IntegrationConfigs.tsx
  ui/src/modules/settings/integrations/components/line/Line.tsx
  ui/src/modules/settings/integrations/components/telegram/Telegram.tsx
  ui/src/modules/settings/integrations/components/twilioSms/TwilioSms.tsx
  ui/src/modules/settings/integrations/components/viber/Viber.tsx
  ui/src/modules/tutorial/components/Tutorial.tsx
Labels: area/ui, type: enhancement

#2452 show external integration data in appstore
  ui/src/modules/settings/integrations/components/common/IntegrationListItem.tsx
Labels: type: enhancement

#2484 Perf doc add invest
  README.md
  docs/.gitignore
  docs/blog/2020-01-08-release-note-v0.12.0.md
  docs/blog/2020-03-017-release-note-v0.13.0.md
  docs/blog/2020-04-02-install-erxes-with-heroku.md
  docs/docs/administrator/system-config.md
  docs/docs/developer/contributing.md
  docs/docs/installation/aws.md
  docs/docs/installation/digitalocean.md
  docs/docs/installation/docker.md
  docs/docs/installation/heroku.md
  docs/docs/installation/ubuntu-quickstart.mdx
  docs/docs/installation/ubuntu-step-by-step.mdx
  docs/docs/installation/ubuntu-troubleshooting.mdx
  docs/docs/installation/ubuntu.mdx
  docs/docs/installation/upgrade.md
  docs/docs/overview/deployment-overview.md
  docs/docs/overview/getting-started.md
  docs/docs/user/engage.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/components/InvestEquity.js
  docs/src/components/InvestFAQ.js
  docs/src/components/investCSO.js
  docs/src/components/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/invest.js
  docs/src/pages/styles.module.css
  docs/static/img/graph.svg
  docs/static/img/graph1.svg
  docs/static/img/graph2.svg
  docs/static/img/invest-chart.svg
  docs/static/img/invest-chart1.svg
  docs/static/img/invest-chart2.png
  docs/static/img/invest-icon.jpg
  docs/static/img/invest-icon1.jpg
  docs/static/img/invest-icon2.jpg
  docs/website/i18n/en.json
  docs/yarn.lock
Labels: area/docs
