Repository erxes/erxes, pull requests merged in 2021-02, with the labels that each got.

#2628 Fix/campaign form
  ui/src/modules/engage/components/EmailForm.tsx
  ui/src/modules/engage/components/MessageList.tsx
  ui/src/modules/engage/components/step/MessageTypeStep.tsx
  ui/src/modules/engage/constants.ts
  ui/src/modules/engage/utils.ts
Labels: type: bug

#2630 Enhancement/campaign draft
  api/src/__tests__/engageMessageDb.test.ts
  api/src/data/resolvers/mutations/engages.ts
  api/src/db/models/Engages.ts
  ui/src/modules/engage/components/AutoAndManualForm.tsx
  ui/src/modules/engage/components/FormBase.tsx
  ui/src/modules/engage/components/MessageListRow.tsx
  ui/src/modules/engage/containers/withFormMutations.tsx
  ui/src/modules/engage/graphql/mutations.ts
Labels: type: enhancement

#2651 Fix form callout preview
  ui/src/modules/leads/components/Lead.tsx
  ui/src/modules/leads/components/step/CallOut.tsx
Labels: area/ui, type: bug

#2654 Enhancement/customer activity log sms
  api/src/__tests__/activityLogQueries.test.ts
  api/src/__tests__/httpEndpoints.test.ts
  api/src/__tests__/integrationMutations.test.ts
  api/src/data/resolvers/mutations/integrations.ts
  api/src/data/resolvers/queries/activityLogs.ts
  api/src/db/models/ActivityLogs.ts
  api/src/db/models/definitions/constants.ts
  api/src/index.ts
  engages-email-sender/package.json
  engages-email-sender/src/__tests__/httpEndpoints.test.ts
  engages-email-sender/yarn.lock
  integrations/src/telnyx/models.ts
  ui/src/modules/activityLogs/components/ActivityItem.tsx
  ui/src/modules/activityLogs/components/items/ConvertLog.tsx
  ui/src/modules/activityLogs/components/items/MergedLog.tsx
  ui/src/modules/activityLogs/components/items/SegmentLog.tsx
  ui/src/modules/activityLogs/components/items/SmsLog.tsx
  ui/src/modules/activityLogs/components/items/archive/ArchiveLog.tsx
  ui/src/modules/activityLogs/components/items/boardItems/AssigneeLog.tsx
  ui/src/modules/activityLogs/components/items/boardItems/MovementLog.tsx
  ui/src/modules/activityLogs/components/items/checklist/ChecklistItem.tsx
  ui/src/modules/activityLogs/components/items/create/BoardItemCreate.tsx
  ui/src/modules/activityLogs/components/items/create/CreatedLog.tsx
  ui/src/modules/activityLogs/components/items/create/CustomerCreate.tsx
  ui/src/modules/activityLogs/components/items/delete/DeletedLog.tsx
  ui/src/modules/activityLogs/types.ts
  ui/src/modules/customers/components/detail/CustomerDetails.tsx
Labels: type: enhancement

#2658 Fix/campaign
  api/src/__tests__/engageMessageDb.test.ts
  api/src/__tests__/engageMessageMutations.test.ts
  api/src/commands/loadTestData.ts
  api/src/data/resolvers/mutations/engageUtils.ts
  api/src/data/resolvers/mutations/engages.ts
  api/src/db/models/definitions/engages.ts
  ui/src/modules/engage/components/MessageListRow.tsx
Labels: type: bug
