Repository erxes/erxes, pull requests merged in 2022-10, with the labels that each got.

#3703 feat(marketplace): init
  packages/core-ui/public/images/no-plugin.png
  packages/core-ui/src/modules/settings/marketplace/components/CollapseFilter.tsx
  packages/core-ui/src/modules/settings/marketplace/components/FormControl.tsx
  packages/core-ui/src/modules/settings/marketplace/components/Installer.tsx
  packages/core-ui/src/modules/settings/marketplace/components/Leftbar.tsx
  packages/core-ui/src/modules/settings/marketplace/components/PluginBox.tsx
  packages/core-ui/src/modules/settings/marketplace/components/PluginPreview.tsx
  packages/core-ui/src/modules/settings/marketplace/components/ServiceBox.tsx
  packages/core-ui/src/modules/settings/marketplace/components/Store.tsx
  packages/core-ui/src/modules/settings/marketplace/components/Wrapper.tsx
  packages/core-ui/src/modules/settings/marketplace/components/detail/PluginDetails.tsx
  packages/core-ui/src/modules/settings/marketplace/components/detail/styles.tsx
  packages/core-ui/src/modules/settings/marketplace/components/styles.tsx
  packages/core-ui/src/modules/settings/marketplace/constants.ts
  packages/core-ui/src/modules/settings/marketplace/containers/PluginDetails.tsx
  packages/core-ui/src/modules/settings/marketplace/containers/Store.tsx
  packages/core-ui/src/modules/settings/marketplace/graphql/index.ts
  packages/core-ui/src/modules/settings/marketplace/graphql/mutations.ts
  packages/core-ui/src/modules/settings/marketplace/graphql/queries.ts
  packages/core-ui/src/modules/settings/marketplace/routes.tsx
  packages/core-ui/src/modules/settings/marketplace/styles.tsx
  packages/erxes-ui/src/components/AsyncComponent.tsx
  packages/plugin-cards-api/src/graphql/schema/board.ts
  packages/plugin-inbox-ui/src/settings/integrations/components/store/Home.tsx
Labels: type: feature

#3706 Temporary segment
  packages/erxes-ui/src/components/filter/Filter.tsx
  packages/plugin-contacts-api/src/coc/utils.ts
  packages/plugin-contacts-api/src/graphql/company.ts
  packages/plugin-contacts-api/src/graphql/customer.ts
  packages/plugin-contacts-api/src/messageBroker.ts
  packages/plugin-contacts-ui/src/companies/components/list/CompaniesList.tsx
  packages/plugin-contacts-ui/src/companies/containers/CompaniesList.tsx
  packages/plugin-contacts-ui/src/customers/components/list/CustomersList.tsx
  packages/plugin-contacts-ui/src/customers/containers/CustomersList.tsx
  packages/plugin-segments-api/src/messageBroker.ts
  packages/ui-contacts/src/companies/graphql/queries.ts
  packages/ui-contacts/src/customers/graphql/queries.ts
  packages/ui-segments/package.json
  packages/ui-segments/src/components/filter/TemporarySegment.tsx
  packages/ui-segments/src/components/form/Form.tsx
  packages/ui-segments/src/components/form/SegmentsForm.tsx
  packages/ui-segments/src/containers/form/SegmentsForm.tsx
Labels: type: enhancement, Hacktoberfest

#3732 show & add email filter to email deliveries
  packages/plugin-engages-api/src/graphql/resolvers/Query.ts
  packages/plugin-engages-api/src/graphql/schema/engage.ts
  packages/plugin-logs-ui/src/emailDelivery/components/EmailDelivery.tsx
  packages/plugin-logs-ui/src/emailDelivery/components/Row.tsx
  packages/plugin-logs-ui/src/emailDelivery/containers/EmailDelivery.tsx
  packages/plugin-logs-ui/src/emailDelivery/queries.ts
Labels: type: enhancement, Hacktoberfest

#3737 close #3736
  packages/plugin-contacts-api/src/utils.ts
  packages/plugin-engages-api/src/sender.ts
Labels: type: enhancement

#3743 Webbuilder api code migration like OS structure
  packages/plugin-webbuilder-api/src/connectionResolver.ts
  packages/plugin-webbuilder-api/src/graphql/resolvers/contentType.ts
  packages/plugin-webbuilder-api/src/graphql/resolvers/mutations.ts
  packages/plugin-webbuilder-api/src/graphql/resolvers/page.ts
  packages/plugin-webbuilder-api/src/graphql/resolvers/queries.ts
  packages/plugin-webbuilder-api/src/graphql/resolvers/utils.ts
  packages/plugin-webbuilder-api/src/models/ContentTypes.ts
  packages/plugin-webbuilder-api/src/models/Entries.ts
  packages/plugin-webbuilder-api/src/models/Pages.ts
  packages/plugin-webbuilder-api/src/models/Sites.ts
  packages/plugin-webbuilder-api/src/models/Templates.ts
  packages/plugin-webbuilder-api/src/models/definitions/contentTypes.ts
  packages/plugin-webbuilder-api/src/models/definitions/entries.ts
  packages/plugin-webbuilder-api/src/models/definitions/pages.ts
  packages/plugin-webbuilder-api/src/models/definitions/sites.ts
  packages/plugin-webbuilder-api/src/models/definitions/templates.ts
  packages/plugin-webbuilder-api/src/models/definitions/utils.ts
  packages/plugin-webbuilder-api/src/models/entries.ts
  packages/plugin-webbuilder-api/src/utils.ts
Labels: type: enhancement, Hacktoberfest

#3744 fix typescript errors and remove unused imports
  packages/plugin-cards-api/src/graphql/resolvers/mutations/deals.ts
  packages/plugin-cards-api/src/graphql/resolvers/mutations/utils.ts
  packages/plugin-cards-api/src/graphql/resolvers/queries/deals.ts
  packages/plugin-inbox-api/src/graphql/resolvers/conversationMutations.ts
  packages/plugin-inbox-api/src/graphql/resolvers/integrationMutations.ts
  packages/plugin-knowledgebase-api/src/graphql/resolvers/knowledgeBaseMutations.ts
  packages/plugin-tags-api/src/graphql/resolvers/queries/tags.ts
Labels: Hacktoberfest

#3747 Convert multiple conversation to single card
  packages/plugin-cards-api/src/graphql/schema/task.ts
  packages/plugin-cards-api/src/graphql/schema/ticket.ts
  packages/plugin-cards-api/src/models/utils.ts
  packages/ui-cards/src/boards/components/portable/AddForm.tsx
Labels: 🐛 bug, Hacktoberfest, hacktoberfest-accepted
