Repository erxes/erxes, pull requests merged in 2022-11, with the labels that each got.

#3787 Fix worker bug
  packages/workers/src/data/utils.ts
  packages/workers/src/worker/import/bulkInsert.worker.ts
  packages/workers/src/worker/import/utils.ts
  packages/workers/src/worker/workerUtil.ts
Labels: 🐛 bug

#3788 Client portal notification
  client-portal/.env.sample
  client-portal/modules/appContext.tsx
  client-portal/modules/common/Avatar.tsx
  client-portal/modules/main/components/DataWithLoader.tsx
  client-portal/modules/main/components/Header.tsx
  client-portal/modules/main/components/Layout.tsx
  client-portal/modules/main/components/notifications/Detail.tsx
  client-portal/modules/main/components/notifications/List.tsx
  client-portal/modules/main/components/notifications/Notifications.tsx
  client-portal/modules/main/components/notifications/Row.tsx
  client-portal/modules/main/components/notifications/Settings.tsx
  client-portal/modules/main/containers/Header.tsx
  client-portal/modules/main/containers/Layout.tsx
  client-portal/modules/main/containers/notifications/Detail.tsx
  client-portal/modules/main/containers/notifications/List.tsx
  client-portal/modules/main/containers/notifications/Settings.tsx
  client-portal/modules/styles/main.ts
  client-portal/modules/task/components/Header.tsx
  client-portal/modules/task/containers/Form.tsx
  client-portal/modules/task/containers/Tasks.tsx
  client-portal/modules/ticket/containers/Form.tsx
  client-portal/modules/ticket/containers/Ticket.tsx
  client-portal/modules/types.ts
  client-portal/modules/user/graphql/queries.ts
  client-portal/modules/user/graphql/subscriptions.ts
  client-portal/modules/utils/index.tsx
  client-portal/package.json
  client-portal/pages/api/lib/initApollo.ts
  client-portal/pages/notification/[id].tsx
  client-portal/pages/tasks/index.tsx
  client-portal/server.js
  client-portal/utils/index.ts
  client-portal/yarn.lock
  packages/plugin-cards-api/src/messageBroker.ts
  packages/plugin-clientportal-api/src/afterMutations.ts
  packages/plugin-clientportal-api/src/afterMutations/cards.ts
  packages/plugin-clientportal-api/src/afterMutations/knowledgeBase.ts
  packages/plugin-clientportal-api/src/configs.ts
  packages/plugin-clientportal-api/src/connectionResolver.ts
  packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortal.ts
  packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortalNotifications.ts
  packages/plugin-clientportal-api/src/graphql/resolvers/mutations/index.ts
  packages/plugin-clientportal-api/src/graphql/resolvers/queries/clientPortal.ts
  packages/plugin-clientportal-api/src/graphql/resolvers/queries/clientPortalNotifications.ts
  packages/plugin-clientportal-api/src/graphql/resolvers/queries/index.ts
  packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
  packages/plugin-clientportal-api/src/graphql/schema/clientPortalNotifications.ts
  packages/plugin-clientportal-api/src/graphql/schema/clientPortalUser.ts
  packages/plugin-clientportal-api/src/graphql/subscriptionPlugin.js
  packages/plugin-clientportal-api/src/graphql/typeDefs.ts
  packages/plugin-clientportal-api/src/messageBroker.ts
  packages/plugin-clientportal-api/src/models/ClientPortalNotifications.ts
  packages/plugin-clientportal-api/src/models/ClientPortalUser.ts
  packages/plugin-clientportal-api/src/models/ClientPortalUserCard.ts
  packages/plugin-clientportal-api/src/models/definitions/clientPortalNotifications.ts
  packages/plugin-clientportal-api/src/models/definitions/clientPortalUser.ts
  packages/plugin-clientportal-api/src/models/definitions/clientPortalUserCards.ts
  packages/plugin-clientportal-api/src/utils.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#3765 Barcodes
  packages/core-ui/public/index.html
  packages/core-ui/public/print.min.css
  packages/plugin-products-api/src/constants.ts
  packages/plugin-products-api/src/dataloaders/resolvers/queries/products.ts
  packages/plugin-products-api/src/essyncer.js
  packages/plugin-products-api/src/exporter.ts
  packages/plugin-products-api/src/graphql/schema/product.ts
  packages/plugin-products-api/src/imports.ts
  packages/plugin-products-api/src/models/Products.ts
  packages/plugin-products-api/src/models/definitions/products.ts
  packages/plugin-products-ui/package.json
  packages/plugin-products-ui/src/components/barcodeGenerator/BarcodeGenerator.tsx
  packages/plugin-products-ui/src/components/barcodeGenerator/LeftSidebar.tsx
  packages/plugin-products-ui/src/components/product/detail/BasicInfo.tsx
  packages/plugin-products-ui/src/containers/barcodeGenerator/BarcodeGenerator.tsx
  packages/plugin-products-ui/src/containers/product/detail/ProductDetails.tsx
  packages/plugin-products-ui/src/routes.tsx
  packages/plugin-products-ui/src/styles.ts
  packages/plugin-products-ui/src/types.ts
  packages/plugin-products-ui/src/utils.tsx
  packages/ui-products/src/components/ProductForm.tsx
  packages/ui-products/src/graphql/mutations.ts
  packages/ui-products/src/graphql/queries.ts
  packages/ui-products/src/styles.ts
  packages/ui-products/src/types.ts
  yarn.lock
Labels: type: feature, area/api, area/ui, status/ready-for-merge

#3848 Development docs improvement
  docs/docs/code-reference/api/common-functions.md
  docs/docs/deployment/deployment/docker-compose.md
  docs/docs/developer/developing-integration-plugins.md
  docs/docs/developer/developing-plugins.md
  docs/sidebars.js
Labels: type: enhancement
